"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import Layout from '../components/Layout';
import { Card, CardHeader, CardTitle, CardContent } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Brain, Target, Zap, TrendingUp, Calendar, ArrowRight, CheckCircle2, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
const Strategy = () => {
    const [generating, setGenerating] = React.useState(false);
    const handleGenerateStrategy = () => {
        setGenerating(true);
        toast.promise(new Promise((resolve) => setTimeout(resolve, 3000)), {
            loading: 'IA analisando Brand Kit e tendências de mercado...',
            success: 'Estratégia trimestral gerada com sucesso!',
            error: 'Erro ao gerar estratégia.',
        });
        setTimeout(() => setGenerating(false), 3000);
    };
    return (_jsxs(Layout, { children: [_jsxs("div", { className: "flex justify-between items-center mb-8", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-bold text-slate-900", children: "Estrat\u00E9gia de Marketing" }), _jsx("p", { className: "text-slate-500", children: "Seu roadmap de crescimento personalizado pela nossa IA." })] }), _jsxs(Button, { className: "bg-purple-600 hover:bg-purple-700", onClick: handleGenerateStrategy, disabled: generating, children: [_jsx(Sparkles, { className: "mr-2 h-4 w-4" }), " ", generating ? 'Gerando...' : 'Atualizar Estratégia'] })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-8", children: [_jsxs("div", { className: "lg:col-span-2 space-y-8", children: [_jsxs(Card, { className: "bg-white border-slate-200 shadow-sm overflow-hidden", children: [_jsx("div", { className: "h-2 bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500" }), _jsx(CardHeader, { children: _jsxs("div", { className: "flex justify-between items-start", children: [_jsx(CardTitle, { className: "text-xl font-bold", children: "Plano de A\u00E7\u00E3o: Q3 2024" }), _jsx(Badge, { className: "bg-green-100 text-green-700 border-none", children: "Foco: Convers\u00E3o" })] }) }), _jsxs(CardContent, { className: "space-y-6", children: [_jsxs("div", { className: "p-4 bg-slate-50 rounded-xl border border-slate-100", children: [_jsxs("h4", { className: "font-bold text-slate-900 mb-2 flex items-center", children: [_jsx(Target, { className: "mr-2 text-blue-600", size: 18 }), " Objetivo Principal"] }), _jsx("p", { className: "text-sm text-slate-600 leading-relaxed", children: "Aumentar a taxa de convers\u00E3o em 25% atrav\u00E9s de campanhas de retargeting din\u00E2mico e otimiza\u00E7\u00E3o de landing pages para o p\u00FAblico \"Mariana, 28\"." })] }), _jsxs("div", { className: "space-y-4", children: [_jsx("h4", { className: "font-bold text-slate-900", children: "Marcos Estrat\u00E9gicos" }), [
                                                        { month: 'Julho', task: 'Lançamento da Coleção Inverno com foco em Influenciadores de Moda.', status: 'Em Andamento' },
                                                        { month: 'Agosto', task: 'Implementação de automação de carrinho abandonado via WhatsApp.', status: 'Pendente' },
                                                        { month: 'Setembro', task: 'Campanha de antecipação Black Friday com lista VIP de leads.', status: 'Pendente' },
                                                    ].map((milestone, i) => (_jsxs("div", { className: "flex items-start space-x-4 p-3 rounded-lg hover:bg-slate-50 transition-colors", children: [_jsx("div", { className: "w-20 flex-shrink-0", children: _jsx("span", { className: "text-xs font-bold text-slate-400 uppercase", children: milestone.month }) }), _jsx("div", { className: "flex-1", children: _jsx("p", { className: "text-sm font-medium text-slate-700", children: milestone.task }) }), _jsx(Badge, { variant: "outline", className: "text-[10px]", children: milestone.status })] }, i)))] })] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs(Card, { className: "bg-white border-slate-200 shadow-sm", children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "text-lg font-bold flex items-center", children: [_jsx(Zap, { className: "mr-2 text-orange-500", size: 20 }), " Canais Recomendados"] }) }), _jsx(CardContent, { className: "space-y-4", children: [
                                                    { channel: 'Instagram Reels', weight: 45, reason: 'Alto engajamento do público jovem.' },
                                                    { channel: 'Google Search', weight: 30, reason: 'Captura de demanda direta por produtos.' },
                                                    { channel: 'TikTok Ads', weight: 25, reason: 'Escalabilidade e baixo custo por mil (CPM).' },
                                                ].map((item, i) => (_jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex justify-between text-xs font-bold", children: [_jsx("span", { className: "text-slate-700", children: item.channel }), _jsxs("span", { className: "text-blue-600", children: [item.weight, "%"] })] }), _jsx("div", { className: "w-full bg-slate-100 h-1.5 rounded-full overflow-hidden", children: _jsx("div", { className: "bg-blue-500 h-full", style: { width: `${item.weight}%` } }) }), _jsx("p", { className: "text-[10px] text-slate-400", children: item.reason })] }, i))) })] }), _jsxs(Card, { className: "bg-white border-slate-200 shadow-sm", children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "text-lg font-bold flex items-center", children: [_jsx(TrendingUp, { className: "mr-2 text-green-600", size: 20 }), " Metas Estimadas"] }) }), _jsx(CardContent, { className: "space-y-4", children: [
                                                    { label: 'Novos Leads', value: '+2.400', trend: 'up' },
                                                    { label: 'Custo por Lead', value: 'R$ 6,50', trend: 'down' },
                                                    { label: 'ROI Projetado', value: '5.5x', trend: 'up' },
                                                ].map((meta, i) => (_jsxs("div", { className: "flex items-center justify-between p-3 bg-slate-50 rounded-lg", children: [_jsx("span", { className: "text-xs font-medium text-slate-600", children: meta.label }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("span", { className: "text-sm font-bold text-slate-900", children: meta.value }), _jsx("div", { className: `w-2 h-2 rounded-full ${meta.trend === 'up' ? 'bg-green-500' : 'bg-blue-500'}` })] })] }, i))) })] })] })] }), _jsxs("div", { className: "space-y-6", children: [_jsxs(Card, { className: "bg-slate-900 text-white border-none shadow-lg", children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "text-lg font-bold flex items-center", children: [_jsx(Brain, { className: "mr-2 text-purple-400", size: 20 }), " Insights da IA"] }) }), _jsxs(CardContent, { className: "space-y-4", children: [_jsxs("div", { className: "p-3 bg-white/10 rounded-lg border border-white/10", children: [_jsx("p", { className: "text-xs font-bold text-purple-400 uppercase mb-1", children: "Oportunidade de Conte\u00FAdo" }), _jsx("p", { className: "text-sm text-slate-300", children: "V\u00EDdeos de \"Bastidores\" est\u00E3o performando 3x melhor que fotos est\u00E1ticas para sua marca. Foque em Stories aut\u00EAnticos." })] }), _jsxs("div", { className: "p-3 bg-white/10 rounded-lg border border-white/10", children: [_jsx("p", { className: "text-xs font-bold text-orange-400 uppercase mb-1", children: "Alerta de Audi\u00EAncia" }), _jsx("p", { className: "text-sm text-slate-300", children: "Houve um aumento de 15% no interesse por \"Moda Sustent\u00E1vel\" entre seus seguidores. Considere adaptar sua copy." })] }), _jsx(Button, { className: "w-full bg-blue-600 hover:bg-blue-700 border-none", children: "Aplicar Recomenda\u00E7\u00F5es" })] })] }), _jsxs(Card, { className: "bg-white border-slate-200 shadow-sm", children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-lg font-bold", children: "Checklist de Sucesso" }) }), _jsx(CardContent, { className: "space-y-3", children: [
                                            'Configurar Pixel de Conversão',
                                            'Validar Brand Kit com a Equipe',
                                            'Conectar Google Ads',
                                            'Subir Criativos de Inverno',
                                            'Definir Orçamento Diário'
                                        ].map((item, i) => (_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("div", { className: `w-5 h-5 rounded-full border flex items-center justify-center ${i < 2 ? 'bg-green-500 border-green-500 text-white' : 'border-slate-200'}`, children: i < 2 && _jsx(CheckCircle2, { size: 12 }) }), _jsx("span", { className: `text-xs ${i < 2 ? 'text-slate-400 line-through' : 'text-slate-600'}`, children: item })] }, i))) })] })] })] })] }));
};
export default Strategy;
//# sourceMappingURL=Strategy.js.map