"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import Layout from '../components/Layout';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { Switch } from '../components/ui/switch';
import { Zap, Mail, MessageSquare, Bell, MoreVertical, PlayCircle, Clock } from 'lucide-react';
import CreateWorkflowModal from '../components/CreateWorkflowModal';
const initialWorkflows = [
    { id: 1, name: 'Boas-vindas Instagram', trigger: 'Novo Lead', action: 'Enviar E-mail', status: true, runs: 145, lastRun: '10 min atrás', icon: Mail, color: 'text-blue-600', bg: 'bg-blue-50' },
    { id: 2, name: 'Alerta de Orçamento Crítico', trigger: 'Gasto > 90%', action: 'Notificar Admin', status: true, runs: 12, lastRun: '2 dias atrás', icon: Bell, color: 'text-orange-600', bg: 'bg-orange-50' },
    { id: 3, name: 'Qualificação Automática', trigger: 'Novo Lead TikTok', action: 'Mudar Status', status: false, runs: 0, lastRun: 'Nunca', icon: Zap, color: 'text-purple-600', bg: 'bg-purple-50' },
    { id: 4, name: 'Follow-up 24h', trigger: 'Lead Sem Contato', action: 'Enviar WhatsApp', status: true, runs: 89, lastRun: '1 hora atrás', icon: MessageSquare, color: 'text-green-600', bg: 'bg-green-50' },
];
const Workflows = () => {
    return (_jsxs(Layout, { children: [_jsxs("div", { className: "flex justify-between items-center mb-8", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-bold text-slate-900", children: "Automa\u00E7\u00F5es" }), _jsx("p", { className: "text-slate-500", children: "Crie fluxos inteligentes para otimizar seu marketing." })] }), _jsx(CreateWorkflowModal, {})] }), _jsx("div", { className: "grid grid-cols-1 gap-4", children: initialWorkflows.map((flow) => (_jsx(Card, { className: "bg-white border-slate-200 shadow-sm hover:border-purple-200 transition-colors", children: _jsx(CardContent, { className: "p-6", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("div", { className: `p-3 rounded-xl ${flow.bg} ${flow.color}`, children: _jsx(flow.icon, { size: 24 }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-slate-900", children: flow.name }), _jsxs("div", { className: "flex items-center space-x-3 mt-1", children: [_jsxs("span", { className: "text-xs text-slate-500 flex items-center", children: [_jsx(PlayCircle, { size: 12, className: "mr-1" }), " ", flow.trigger] }), _jsx("span", { className: "text-xs text-slate-300", children: "\u2022" }), _jsxs("span", { className: "text-xs text-slate-500 flex items-center", children: [_jsx(Zap, { size: 12, className: "mr-1" }), " ", flow.action] })] })] })] }), _jsxs("div", { className: "flex items-center space-x-8", children: [_jsxs("div", { className: "text-right hidden md:block", children: [_jsx("p", { className: "text-xs font-bold text-slate-400 uppercase tracking-wider", children: "Execu\u00E7\u00F5es" }), _jsx("p", { className: "text-lg font-bold text-slate-900", children: flow.runs })] }), _jsxs("div", { className: "text-right hidden md:block", children: [_jsx("p", { className: "text-xs font-bold text-slate-400 uppercase tracking-wider", children: "\u00DAltima vez" }), _jsxs("p", { className: "text-sm font-medium text-slate-600 flex items-center justify-end", children: [_jsx(Clock, { size: 12, className: "mr-1" }), " ", flow.lastRun] })] }), _jsxs("div", { className: "flex items-center space-x-4 pl-8 border-l border-slate-100", children: [_jsx(Switch, { defaultChecked: flow.status }), _jsx("button", { className: "text-slate-400 hover:text-slate-600", children: _jsx(MoreVertical, { size: 20 }) })] })] })] }) }) }, flow.id))) })] }));
};
export default Workflows;
//# sourceMappingURL=Workflows.js.map