"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Instagram, Facebook, Chrome, MoreHorizontal, Heart, MessageCircle, Send, Bookmark } from 'lucide-react';
const SocialPreview = ({ content, platform, brandName = "Sua Marca" }) => {
    const renderInstagram = () => (_jsxs("div", { className: "max-w-[350px] mx-auto bg-white border border-slate-200 rounded-lg overflow-hidden shadow-sm", children: [_jsxs("div", { className: "p-3 flex items-center justify-between border-b border-slate-50", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-gradient-to-tr from-yellow-400 to-purple-600 p-0.5", children: _jsx("div", { className: "w-full h-full rounded-full bg-white p-0.5", children: _jsx("div", { className: "w-full h-full rounded-full bg-slate-200" }) }) }), _jsx("span", { className: "text-xs font-bold", children: brandName.toLowerCase().replace(/\s/g, '_') })] }), _jsx(MoreHorizontal, { size: 16, className: "text-slate-400" })] }), _jsx("div", { className: "aspect-square bg-slate-100 flex items-center justify-center text-slate-400", children: _jsx("span", { className: "text-xs font-medium", children: "Imagem do Criativo" }) }), _jsxs("div", { className: "p-3", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx(Heart, { size: 22 }), _jsx(MessageCircle, { size: 22 }), _jsx(Send, { size: 22 })] }), _jsx(Bookmark, { size: 22 })] }), _jsxs("div", { className: "space-y-1", children: [_jsx("p", { className: "text-xs font-bold", children: "1.240 curtidas" }), _jsxs("p", { className: "text-xs leading-relaxed", children: [_jsx("span", { className: "font-bold mr-2", children: brandName.toLowerCase().replace(/\s/g, '_') }), content] }), _jsx("p", { className: "text-[10px] text-slate-400 uppercase mt-2", children: "H\u00E1 2 horas" })] })] })] }));
    const renderFacebook = () => (_jsxs("div", { className: "max-w-[400px] mx-auto bg-white border border-slate-200 rounded-lg overflow-hidden shadow-sm", children: [_jsxs("div", { className: "p-4", children: [_jsxs("div", { className: "flex items-center space-x-2 mb-3", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-slate-200" }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-bold text-blue-600", children: brandName }), _jsx("p", { className: "text-[10px] text-slate-500", children: "Patrocinado \u2022 \uD83C\uDF10" })] })] }), _jsx("p", { className: "text-sm mb-3 whitespace-pre-wrap", children: content })] }), _jsx("div", { className: "aspect-video bg-slate-100 flex items-center justify-center text-slate-400 border-y border-slate-100", children: _jsx("span", { className: "text-xs font-medium", children: "Imagem/V\u00EDdeo do An\u00FAncio" }) }), _jsxs("div", { className: "p-3 bg-slate-50 flex justify-between items-center", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[10px] text-slate-500 uppercase", children: "WWW.SUAMARCA.COM" }), _jsx("p", { className: "text-sm font-bold", children: "T\u00EDtulo do An\u00FAncio" })] }), _jsx("button", { className: "px-4 py-1.5 bg-slate-200 rounded text-xs font-bold", children: "Saiba Mais" })] })] }));
    const renderGoogle = () => (_jsxs("div", { className: "max-w-[500px] mx-auto bg-white p-4 border border-slate-200 rounded-lg shadow-sm", children: [_jsxs("div", { className: "flex items-center space-x-2 mb-1", children: [_jsx("div", { className: "w-4 h-4 rounded-full bg-slate-100 flex items-center justify-center text-[8px] font-bold", children: "Ad" }), _jsx("span", { className: "text-xs text-slate-600", children: "https://www.suamarca.com" })] }), _jsxs("h3", { className: "text-blue-700 text-lg font-medium hover:underline cursor-pointer mb-1", children: [content.split('\n')[0].substring(0, 60), "..."] }), _jsx("p", { className: "text-sm text-slate-600 line-clamp-2", children: content.length > 60 ? content.substring(60) : content })] }));
    return (_jsxs("div", { className: "p-8 bg-slate-100 rounded-2xl border border-slate-200 flex items-center justify-center min-h-[500px]", children: [platform === 'instagram' && renderInstagram(), platform === 'facebook' && renderFacebook(), platform === 'google' && renderGoogle(), platform !== 'instagram' && platform !== 'facebook' && platform !== 'google' && (_jsx("div", { className: "text-center text-slate-400", children: _jsx("p", { className: "text-sm", children: "Preview n\u00E3o dispon\u00EDvel para esta plataforma." }) }))] }));
};
export default SocialPreview;
//# sourceMappingURL=SocialPreview.js.map